name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    paths: ["src/**","pom.xml","Justfile",".github/workflows/*"]
  pull_request:
    branches: [ "main" ]
    paths: ["src/**","pom.xml","Justfile",".github/workflows/*"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: [17,21]
        exclude:
          - os: windows-latest
            java-version: 17
            
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup just
        uses: taiki-e/install-action@just

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "${{ matrix.java-version }}"
          cache: maven

      - name: Build & Test (with coverage)
        run: just test

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "surefire-reports-${{ matrix.os }}-java-${{ matrix.java-version}}"
          path: target/surefire-reports

      - name: Upload JaCoCo HTML (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "jacoco-site-${{ matrix.os }}-java-${{ matrix.java-version}}"
          path: target/site/jacoco

      - name: SonarCloud Scan
        if: ${{ matrix.os == "ubuntu-latest" && matrix.java-version == 21}}
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # explicit params if auto-detect fails:
          # projectKey: your_org_your_project
          # organization: your_org 
          args: >
             -Dsonar.projectKey=SyselMitY_cicd-BA-uebung01-sysel
             -Dsonar.organization=syselmity
             -Dsonar.branch.name=main
             -Dsonar.java.binaries=target/classes
             -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
